# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from app_controller import AppController


class App(object):
    def __init__(self):
        super().__init__()
        self.__app_controller = AppController()
        self.__file = None

    def setupUi(self, Practica):
        self.__main_window = Practica
        Practica.setObjectName("Practica")
        Practica.setEnabled(True)
        Practica.resize(375, 480)
        self.centralwidget = QtWidgets.QWidget(Practica)
        self.centralwidget.setObjectName("centralwidget")
        self.selected_method = QtWidgets.QComboBox(self.centralwidget)
        self.selected_method.setGeometry(QtCore.QRect(10, 40, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selected_method.setFont(font)
        self.selected_method.setObjectName("selected_method")
        self.selected_method.addItem("")
        self.selected_method.addItem("")
        self.selected_method.addItem("")
        self.selected_method.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 160, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 270, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(90, 370, 161, 31))
        self.calculate_button.setObjectName("calculate_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 240, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Practica.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Practica)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Practica.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(Practica)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Practica)
        QtCore.QMetaObject.connectSlotsByName(Practica)

        self.__add_funcs()
    
    def __choose_file(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self.__main_window ,"QFileDialog.getOpenFileName()", "","All Files (*);;Python Files (*.py)", options=options)
        self.__file = fileName

    def __start_calc(self):
        if self.__file:
            self.__app_controller.calculate(self.__file, self.selected_method.currentIndex)

    def __add_funcs(self):
        self.calculate_button.clicked.connect(self.__start_calc)
        self.action.triggered.connect(self.__choose_file)

    def retranslateUi(self, Practica):
        _translate = QtCore.QCoreApplication.translate
        Practica.setWindowTitle(_translate("Practica", "MainWindow"))
        self.selected_method.setItemText(0, _translate("Practica", "Статистичний розподіл частот"))
        self.selected_method.setItemText(1, _translate("Practica", "Стат. відносний розподіл частот"))
        self.selected_method.setItemText(2, _translate("Practica", "Стат. розподіл накопичувальних частот"))
        self.selected_method.setItemText(3, _translate("Practica", "Стат. розподіл відносних нак. частот"))
        self.comboBox_2.setItemText(0, _translate("Practica", "За алфавітом"))
        self.comboBox_2.setItemText(1, _translate("Practica", "За голосними"))
        self.comboBox_2.setItemText(2, _translate("Practica", "За приголосними"))
        self.comboBox_2.setItemText(3, _translate("Practica", "Окремі літери"))
        self.comboBox_2.setItemText(4, _translate("Practica", "Довжина слів"))
        self.comboBox_2.setItemText(5, _translate("Practica", "Довжина речень"))
        self.comboBox_3.setItemText(0, _translate("Practica", "Українська"))
        self.comboBox_3.setItemText(1, _translate("Practica", "російська"))
        self.comboBox_3.setItemText(2, _translate("Practica", "Угорська"))
        self.comboBox_3.setItemText(3, _translate("Practica", "Словацька"))
        self.comboBox_3.setItemText(4, _translate("Practica", "Чеська"))
        self.comboBox_3.setItemText(5, _translate("Practica", "Німецька"))
        self.comboBox_3.setItemText(6, _translate("Practica", "Румунська"))
        self.comboBox_3.setItemText(7, _translate("Practica", "Польська"))
        self.calculate_button.setText(_translate("Practica", "РОЗРАХУВАТИ"))
        self.label.setText(_translate("Practica", "Мова:"))
        self.label_2.setText(_translate("Practica", "Ознака:"))
        self.label_3.setText(_translate("Practica", "Операція"))
        self.menu.setTitle(_translate("Practica", "Файл"))
        self.action.setText(_translate("Practica", "Відкрити файл "))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = App()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
