# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Універ\Практика\proctica\resultAllOptions2col.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 448)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 140))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 140))
        self.label_2.setStyleSheet("background-color: #007bd1;")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color:black;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.val1 = QtWidgets.QLabel(Form)
        self.val1.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val1.setFont(font)
        self.val1.setStyleSheet("color:black;\n"
"\n"
"")
        self.val1.setText("")
        self.val1.setObjectName("val1")
        self.verticalLayout.addWidget(self.val1)
        self.val2 = QtWidgets.QLabel(Form)
        self.val2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val2.setFont(font)
        self.val2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val2.setText("")
        self.val2.setObjectName("val2")
        self.verticalLayout.addWidget(self.val2)
        self.val3 = QtWidgets.QLabel(Form)
        self.val3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val3.setFont(font)
        self.val3.setStyleSheet("color:black;\n"
"\n"
"")
        self.val3.setText("")
        self.val3.setObjectName("val3")
        self.verticalLayout.addWidget(self.val3)
        self.val4 = QtWidgets.QLabel(Form)
        self.val4.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val4.setFont(font)
        self.val4.setStyleSheet("color:black;\n"
"\n"
"")
        self.val4.setText("")
        self.val4.setObjectName("val4")
        self.verticalLayout.addWidget(self.val4)
        self.val5 = QtWidgets.QLabel(Form)
        self.val5.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val5.setFont(font)
        self.val5.setStyleSheet("color:black;\n"
"\n"
"")
        self.val5.setText("")
        self.val5.setObjectName("val5")
        self.verticalLayout.addWidget(self.val5)
        self.val6 = QtWidgets.QLabel(Form)
        self.val6.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val6.setFont(font)
        self.val6.setStyleSheet("color:black;\n"
"\n"
"")
        self.val6.setText("")
        self.val6.setObjectName("val6")
        self.verticalLayout.addWidget(self.val6)
        self.val7 = QtWidgets.QLabel(Form)
        self.val7.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val7.setFont(font)
        self.val7.setStyleSheet("color:black;\n"
"\n"
"")
        self.val7.setText("")
        self.val7.setObjectName("val7")
        self.verticalLayout.addWidget(self.val7)
        self.val8 = QtWidgets.QLabel(Form)
        self.val8.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val8.setFont(font)
        self.val8.setStyleSheet("color:black;\n"
"\n"
"")
        self.val8.setText("")
        self.val8.setObjectName("val8")
        self.verticalLayout.addWidget(self.val8)
        self.val9 = QtWidgets.QLabel(Form)
        self.val9.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val9.setFont(font)
        self.val9.setStyleSheet("color:black;\n"
"\n"
"")
        self.val9.setText("")
        self.val9.setObjectName("val9")
        self.verticalLayout.addWidget(self.val9)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.val1_2 = QtWidgets.QLabel(Form)
        self.val1_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val1_2.setFont(font)
        self.val1_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val1_2.setText("")
        self.val1_2.setObjectName("val1_2")
        self.verticalLayout_2.addWidget(self.val1_2)
        self.val2_2 = QtWidgets.QLabel(Form)
        self.val2_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val2_2.setFont(font)
        self.val2_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val2_2.setText("")
        self.val2_2.setObjectName("val2_2")
        self.verticalLayout_2.addWidget(self.val2_2)
        self.val3_2 = QtWidgets.QLabel(Form)
        self.val3_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val3_2.setFont(font)
        self.val3_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val3_2.setText("")
        self.val3_2.setObjectName("val3_2")
        self.verticalLayout_2.addWidget(self.val3_2)
        self.val4_2 = QtWidgets.QLabel(Form)
        self.val4_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val4_2.setFont(font)
        self.val4_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val4_2.setText("")
        self.val4_2.setObjectName("val4_2")
        self.verticalLayout_2.addWidget(self.val4_2)
        self.val5_2 = QtWidgets.QLabel(Form)
        self.val5_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val5_2.setFont(font)
        self.val5_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val5_2.setText("")
        self.val5_2.setObjectName("val5_2")
        self.verticalLayout_2.addWidget(self.val5_2)
        self.val6_2 = QtWidgets.QLabel(Form)
        self.val6_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val6_2.setFont(font)
        self.val6_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val6_2.setText("")
        self.val6_2.setObjectName("val6_2")
        self.verticalLayout_2.addWidget(self.val6_2)
        self.val7_2 = QtWidgets.QLabel(Form)
        self.val7_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val7_2.setFont(font)
        self.val7_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val7_2.setText("")
        self.val7_2.setObjectName("val7_2")
        self.verticalLayout_2.addWidget(self.val7_2)
        self.val8_2 = QtWidgets.QLabel(Form)
        self.val8_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val8_2.setFont(font)
        self.val8_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val8_2.setText("")
        self.val8_2.setObjectName("val8_2")
        self.verticalLayout_2.addWidget(self.val8_2)
        self.val9_2 = QtWidgets.QLabel(Form)
        self.val9_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val9_2.setFont(font)
        self.val9_2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val9_2.setText("")
        self.val9_2.setObjectName("val9_2")
        self.verticalLayout_2.addWidget(self.val9_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:white;\n"
"border:2px solid #007bd1;\n"
"background:#007bd1;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Результати обчислювань:"))
        self.pushButton.setText(_translate("Form", "Готово"))
