# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Універ\Практика\proctica\resultViushka2table.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 417)
        Form.setStyleSheet("background:#22222e;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("font-size:15px;\n"
"gridline-color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.tableView_2 = QtWidgets.QTableView(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tableView_2.setFont(font)
        self.tableView_2.setStyleSheet("font-size:15px;\n"
"gridline-color: rgb(255, 255, 255);")
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout.addWidget(self.tableView_2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableView_3 = QtWidgets.QTableView(Form)
        self.tableView_3.setStyleSheet("font-size:15px;\n"
"gridline-color: rgb(255, 255, 255);")
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout.addWidget(self.tableView_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tableView_4 = QtWidgets.QTableView(Form)
        self.tableView_4.setStyleSheet("font-size:15px;\n"
"gridline-color: rgb(255, 255, 255);")
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout.addWidget(self.tableView_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white;\n"
"background:#22222e;\n"
"border:1px solid white;\n"
"border-radius:30;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Розрахунки:"))
        self.label_2.setText(_translate("Form", "Топ 10 таблиці 1"))
        self.label_3.setText(_translate("Form", "Топ 10 таблиці 2"))
        self.pushButton.setText(_translate("Form", "На головну"))
