# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Універ\Практика\proctica\resultAllOptions1col.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 453)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 140))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 140))
        self.label_2.setStyleSheet("background-color: #007bd1;")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color:black;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.val1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val1.setFont(font)
        self.val1.setStyleSheet("color:black;\n"
"\n"
"")
        self.val1.setText("")
        self.val1.setObjectName("val1")
        self.verticalLayout_2.addWidget(self.val1)
        self.val6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val6.setFont(font)
        self.val6.setStyleSheet("color:black;\n"
"\n"
"")
        self.val6.setText("")
        self.val6.setObjectName("val6")
        self.verticalLayout_2.addWidget(self.val6)
        self.val5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val5.setFont(font)
        self.val5.setStyleSheet("color:black;\n"
"\n"
"")
        self.val5.setText("")
        self.val5.setObjectName("val5")
        self.verticalLayout_2.addWidget(self.val5)
        self.val3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val3.setFont(font)
        self.val3.setStyleSheet("color:black;\n"
"\n"
"")
        self.val3.setText("")
        self.val3.setObjectName("val3")
        self.verticalLayout_2.addWidget(self.val3)
        self.val2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val2.setFont(font)
        self.val2.setStyleSheet("color:black;\n"
"\n"
"")
        self.val2.setText("")
        self.val2.setObjectName("val2")
        self.verticalLayout_2.addWidget(self.val2)
        self.val4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val4.setFont(font)
        self.val4.setStyleSheet("color:black;\n"
"\n"
"")
        self.val4.setText("")
        self.val4.setObjectName("val4")
        self.verticalLayout_2.addWidget(self.val4)
        self.val7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.val7.setFont(font)
        self.val7.setStyleSheet("color:black;\n"
"\n"
"")
        self.val7.setText("")
        self.val7.setObjectName("val7")
        self.verticalLayout_2.addWidget(self.val7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:white;\n"
"border:2px solid #007bd1;\n"
"background:#007bd1;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Результати обчислювань:"))
        self.pushButton.setText(_translate("Form", "Готово"))
