# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Універ\Практика\proctica\resultAllOptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 350)
        Form.setStyleSheet("background:#22222e;\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setStyleSheet("background-color: rgb(251, 91, 93);")
        self.photo.setText("")
        self.photo.setTextFormat(QtCore.Qt.RichText)
        self.photo.setPixmap(QtGui.QPixmap("d:\\Універ\\Практика\\proctica\\checklist.png"))
        self.photo.setScaledContents(False)
        self.photo.setAlignment(QtCore.Qt.AlignCenter)
        self.photo.setObjectName("photo")
        self.verticalLayout_2.addWidget(self.photo)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.inp1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp1.setFont(font)
        self.inp1.setStyleSheet("color:white;")
        self.inp1.setText("")
        self.inp1.setObjectName("inp1")
        self.verticalLayout_2.addWidget(self.inp1)
        self.inp2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp2.setFont(font)
        self.inp2.setStyleSheet("color:white;")
        self.inp2.setText("")
        self.inp2.setObjectName("inp2")
        self.verticalLayout_2.addWidget(self.inp2)
        self.inp3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp3.setFont(font)
        self.inp3.setStyleSheet("color:white;")
        self.inp3.setText("")
        self.inp3.setObjectName("inp3")
        self.verticalLayout_2.addWidget(self.inp3)
        self.inp4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp4.setFont(font)
        self.inp4.setStyleSheet("color:white;")
        self.inp4.setText("")
        self.inp4.setObjectName("inp4")
        self.verticalLayout_2.addWidget(self.inp4)
        self.inp5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp5.setFont(font)
        self.inp5.setStyleSheet("color:white;")
        self.inp5.setText("")
        self.inp5.setObjectName("inp5")
        self.verticalLayout_2.addWidget(self.inp5)
        self.inp6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inp6.setFont(font)
        self.inp6.setStyleSheet("color:white;")
        self.inp6.setText("")
        self.inp6.setObjectName("inp6")
        self.verticalLayout_2.addWidget(self.inp6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white;\n"
"background:#22222e;\n"
"border:1px solid white;\n"
"border-radius:30;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Результати обчислювань:"))
        self.pushButton.setText(_translate("Form", "Готово"))
