# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Універ\Практика\proctica\resultViushka4table.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 417)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("gridline-color: #007bd1;")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.tableView_2 = QtWidgets.QTableView(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tableView_2.setFont(font)
        self.tableView_2.setStyleSheet("gridline-color: #007bd1;")
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout.addWidget(self.tableView_2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableView_3 = QtWidgets.QTableView(Form)
        self.tableView_3.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tableView_3.setFont(font)
        self.tableView_3.setStyleSheet("gridline-color: #007bd1;")
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout.addWidget(self.tableView_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tableView_4 = QtWidgets.QTableView(Form)
        self.tableView_4.setMaximumSize(QtCore.QSize(16777215, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tableView_4.setFont(font)
        self.tableView_4.setStyleSheet("gridline-color:#007bd1;")
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout.addWidget(self.tableView_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:white;\n"
"border:2px solid #007bd1;\n"
"background:#007bd1;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Розрахунки:"))
        self.label_2.setText(_translate("Form", "10 значень з найбільшою частотою (Табл.1)"))
        self.label_3.setText(_translate("Form", "10 значень з найбільшою частотою (Табл.2)"))
        self.pushButton.setText(_translate("Form", "На головну"))
